#!/usr/bin/env python
#
# GUI module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 30, 2018 02:49:06 PM
#
# Refactored for better maintainability, explicit imports,
# and improved code style.

"""
notepad.py – Main GUI for the Notepad application.

This module creates the graphical interface using tkinter and ttk.
It provides tabs for adding, displaying, and managing notes.
The backend logic is handled by notepad_support.py.
"""

import sys
from tkinter import WORD, Button, Entry, Frame, Label, Text, Tk, Toplevel, ttk

import notepad_support

# Global variables (used by the PAGE-generated structure)
w = None  # Toplevel window reference
w_win = None  # Alias for w (kept for compatibility)
rt = None  # Root window reference


def vp_start_gui():
    """
    Start the GUI application as the main routine.

    This is the entry point when the module is run directly.
    """
    global w, root
    root = Tk()
    root.resizable(False, False)
    top = NotepadsManagement(root)
    notepad_support.init(root, top)
    root.mainloop()


def create_Notepads_managment(root, *args, **kwargs):
    """
    Create a new NotepadsManagement window as a Toplevel.

    This is used when the module is imported by another program.

    Args:
        root: The parent Tkinter root window.
        *args, **kwargs: Additional arguments passed to the support init.

    Returns:
        tuple: (Toplevel window, NotepadsManagement instance)
    """
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = NotepadsManagement(w)
    notepad_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Notepads_managment():
    """Destroy the main Toplevel window and release the reference."""
    global w
    if w:
        w.destroy()
        w = None


class NotepadsManagement:
    """
    Main GUI class for the Notepads management application.

    This class sets up the notebook (tabbed interface) with three tabs:
        - Add: Input fields for title and content, with Add/Clear buttons.
        - Display: Search and navigation through existing notes.
        - Create: Button to initialize the database table.

    Attributes:
        style (ttk.Style): The ttk style object for theming.
        TNotebook1 (ttk.Notebook): The main notebook widget.
        inputNotice, inputTitle, outputNotice, inputSearchTitle: Various
            entry and text widgets.
        Button2, Button3, Button4, Button5, Button7, Button8, Button6, Button1:
            Button widgets with respective callbacks.
        Label1, Label2, Label3, Label4: Label widgets for descriptions.
        errorOutput (Label): Label for displaying status/error messages.
    """

    def __init__(self, top):
        """
        Initialize the GUI layout.

        Args:
            top: The parent Tkinter window (either Tk or Toplevel).
        """
        self.top = top
        self._setup_style()
        self._create_widgets()
        self._place_widgets()
        self._bind_events()

    def _setup_style(self):
        """Configure the ttk style for the application."""
        _bgcolor = "#d9d9d9"  # gray85
        _fgcolor = "#000000"
        _compcolor = "#d9d9d9"
        _ana2color = "#d9d9d9"

        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use("winnative")
        self.style.configure(".", background=_bgcolor)
        self.style.configure(".", foreground=_fgcolor)
        self.style.configure(".", font="TkDefaultFont")
        self.style.map(
            ".", background=[("selected", _compcolor), ("active", _ana2color)]
        )

        # Notebook tabs
        self.style.configure("TNotebook.Tab", background=_bgcolor)
        self.style.configure("TNotebook.Tab", foreground=_fgcolor)
        self.style.map(
            "TNotebook.Tab",
            background=[("selected", _compcolor), ("active", _ana2color)],
        )

    def _create_widgets(self):
        """Create all GUI widgets (without placing them yet)."""
        # Main window configuration
        self.top.geometry("600x450")
        self.top.title("Notepads management")
        self.top.configure(highlightcolor="black")

        # Notebook
        self.TNotebook1 = ttk.Notebook(self.top)
        self.TNotebook1.configure(width=582, takefocus="")

        # Tab 0: Add
        self.tab0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.tab0, padding=3, text="Add")

        # Tab 1: Display
        self.tab1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.tab1, padding=3, text="Display")

        # Tab 2: Create
        self.tab2 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.tab2, padding=3, text="Create")

        # ---- Tab0 widgets ----
        self.inputNotice = Text(
            self.tab0,
            background="white",
            font="TkTextFont",
            selectbackground="#c4c4c4",
            width=396,
            wrap=WORD,
        )

        self.inputTitle = Entry(
            self.tab0,
            background="white",
            font="TkFixedFont",
            selectbackground="#c4c4c4",
        )

        self.Label1 = Label(self.tab0, text="Title", activebackground="#f9f9f9")

        self.Label2 = Label(self.tab0, text="Notice:", activebackground="#f9f9f9")

        self.Button2 = Button(self.tab0, text="Add", activebackground="#d9d9d9")
        self.Button3 = Button(self.tab0, text="Clear", activebackground="#d9d9d9")

        # ---- Tab1 widgets ----
        self.outputNotice = Text(
            self.tab1,
            background="white",
            font="TkTextFont",
            selectbackground="#c4c4c4",
            width=346,
            wrap=WORD,
        )

        self.inputSearchTitle = Entry(
            self.tab1,
            background="white",
            font="TkFixedFont",
            selectbackground="#c4c4c4",
        )

        self.Label3 = Label(self.tab1, text="Title", activebackground="#f9f9f9")

        self.Button4 = Button(self.tab1, text="Next", activebackground="#d9d9d9")
        self.Button5 = Button(self.tab1, text="Back", activebackground="#d9d9d9")
        self.Button7 = Button(self.tab1, text="Search", activebackground="#d9d9d9")
        self.Button8 = Button(self.tab1, text="Delete", activebackground="#d9d9d9")

        # ---- Tab2 widgets ----
        self.Label4 = Label(
            self.tab2,
            text="For creating a new notepads managment.",
            activebackground="#f9f9f9",
        )

        self.Button6 = Button(self.tab2, text="Create", activebackground="#d9d9d9")

        # ---- Main window widgets (outside notebook) ----
        self.Button1 = Button(self.top, text="Exit", activebackground="#d9d9d9")
        self.errorOutput = Label(self.top, activebackground="#f9f9f9")

    def _place_widgets(self):
        """Place all widgets using place() or grid() (currently using place())."""
        self.TNotebook1.place(relx=0.02, rely=0.02, relheight=0.85, relwidth=0.97)

        # ---- Tab0 placements ----
        self.inputNotice.place(relx=0.02, rely=0.28, relheight=0.64, relwidth=0.68)
        self.inputTitle.place(relx=0.09, rely=0.08, height=20, relwidth=0.6)
        self.Label1.place(relx=0.02, rely=0.08, height=18, width=29)
        self.Label2.place(relx=0.02, rely=0.22, height=18, width=46)
        self.Button2.place(relx=0.74, rely=0.28, height=26, width=50)
        self.Button3.place(relx=0.74, rely=0.39, height=26, width=56)

        # ---- Tab1 placements ----
        self.outputNotice.place(relx=0.02, rely=0.19, relheight=0.76, relwidth=0.6)
        self.inputSearchTitle.place(relx=0.09, rely=0.08, height=20, relwidth=0.51)
        self.Label3.place(relx=0.02, rely=0.08, height=18, width=29)
        self.Button4.place(relx=0.69, rely=0.33, height=26, width=54)
        self.Button5.place(relx=0.69, rely=0.44, height=26, width=55)
        self.Button7.place(relx=0.69, rely=0.22, height=26, width=68)
        self.Button8.place(relx=0.69, rely=0.56, height=26, width=64)

        # ---- Tab2 placements ----
        self.Label4.place(relx=0.09, rely=0.14, height=18, width=259)
        self.Button6.place(relx=0.22, rely=0.25, height=26, width=69)

        # ---- Main window ----
        self.Button1.place(relx=0.4, rely=0.91, height=26, width=117)
        self.errorOutput.place(relx=0.03, rely=0.91, height=18, width=206)

    def _bind_events(self):
        """Bind buttons to their callback functions from notepad_support."""
        # Instead of <Button-1> bind, use command (more standard)
        self.Button2.configure(command=lambda: notepad_support.add_button(None))
        self.Button3.configure(command=lambda: notepad_support.clear_button(None))
        self.Button4.configure(command=lambda: notepad_support.next_button(None))
        self.Button5.configure(command=lambda: notepad_support.back_button(None))
        self.Button7.configure(command=lambda: notepad_support.search_button(None))
        self.Button8.configure(command=lambda: notepad_support.delete_button(None))
        self.Button6.configure(command=lambda: notepad_support.create_button(None))
        self.Button1.configure(command=lambda: notepad_support.exit_button(None))

    # Keep the old naming convention for backward compatibility if needed,
    # but we can also define properties to mimic the original names.
    @property
    def TNotebook1_t0(self):
        return self.tab0

    @property
    def TNotebook1_t1(self):
        return self.tab1

    @property
    def TNotebook1_t2(self):
        return self.tab2


# If run as main, start the GUI
if __name__ == "__main__":
    vp_start_gui()
