#!/usr/bin/env python
#
# Support module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 29, 2018 03:25:00 PM
#
# Refactored for better performance, security, and maintainability.
# Full documentation (Google style) added for all public functions.

"""
notepad_support.py – Backend support for the Notepad GUI application.

This module handles database operations (SQLite) and provides callback
functions for the notepad GUI (created by PAGE). It manages notes storage,
search, navigation, and deletion.
"""

import sqlite3
import sys
from tkinter import END  # explicit imports instead of *

# ----------------------------------------------------------------------
# Database configuration
# ----------------------------------------------------------------------
DB_NAME = "data.db"


def get_db_connection():
    """
    Return a new SQLite connection to the notes database.

    The connection uses `row_factory = sqlite3.Row` for convenient
    dictionary-like access to rows.

    Returns:
        sqlite3.Connection: A connection object to `data.db`.
    """
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn


# Global connection (kept for backward compatibility)
connection = sqlite3.connect(DB_NAME)
cursor = connection.cursor()


class _NotepadState:
    """
    Encapsulates all mutable global state for the notepad support module.

    Attributes:
        w: The main GUI widget (from PAGE).
        top_level: The top-level Tkinter window.
        root: Alias for top_level.
        search (bool): Flag indicating whether a search is active.
        results (list): List of rows (tuples) from the last search.
        index (int): Current position in the search results.
    """

    __slots__ = ("w", "top_level", "root", "search", "results", "index")

    def __init__(self):
        self.w = None
        self.top_level = None
        self.root = None
        self.search = False
        self.results = []
        self.index = 0


_state = _NotepadState()


# ----------------------------------------------------------------------
# Helper functions (internal)
# ----------------------------------------------------------------------
def _update_output_notice(text):
    """
    Replace the content of the output notice widget with the given text.

    Args:
        text (str): The text to display in the output notice area.
    """
    if _state.w and hasattr(_state.w, "outputNotice"):
        _state.w.outputNotice.delete(1.0, END)
        _state.w.outputNotice.insert(1.0, text)


def _set_error_message(msg):
    """
    Set the error message label in the GUI.

    Args:
        msg (str): The error or status message to display.
    """
    if _state.w and hasattr(_state.w, "errorOutput"):
        _state.w.errorOutput.configure(text=msg)


# ----------------------------------------------------------------------
# Public callback functions (used by the PAGE-generated GUI)
# ----------------------------------------------------------------------


def delete_button(p1):
    """
    Delete the currently selected note from the database.

    The note is identified by the global index into the last search results.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Removes the note from the database.
        - Updates the error message label.
        - Commits the change to the database.
    """
    global cursor, connection
    try:
        if 0 <= _state.index < len(_state.results):
            note_id = _state.results[_state.index][0]
            cursor.execute("DELETE FROM notes WHERE id = ?", (note_id,))
            connection.commit()
            _set_error_message("Note deleted.")
        else:
            _set_error_message("No note selected.")
    except sqlite3.Error as e:
        _set_error_message(f"Database error: {e}")


def create_button(p1):
    """
    Create the `notes` table if it does not already exist.

    This function ensures the database schema is ready. It is safe to call
    multiple times.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Creates the table if missing.
        - Updates the status/error label.
    """
    global cursor, connection
    try:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS notes (
                id INTEGER PRIMARY KEY,
                title TEXT,
                note TEXT
            )
        """)
        connection.commit()
        _set_error_message("Table ready.")
    except sqlite3.Error as e:
        _set_error_message(f"Error creating table: {e}")


def add_button(p1):
    """
    Insert a new note into the database.

    Reads the title and note from the GUI input fields. Both fields must be
    non‑empty. After insertion, the input fields are cleared.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Adds a record to the database.
        - Clears the input fields.
        - Updates the status/error label.
    """
    global cursor, connection
    if not _state.w:
        return
    title = _state.w.inputTitle.get().strip()
    note = _state.w.inputNotice.get(1.0, END).strip()
    if title and note:
        try:
            cursor.execute(
                "INSERT INTO notes (title, note) VALUES (?, ?)", (title, note)
            )
            connection.commit()
            _set_error_message("Note added.")
            # Clear fields
            _state.w.inputTitle.delete(0, END)
            _state.w.inputNotice.delete(1.0, END)
        except sqlite3.Error as e:
            _set_error_message(f"Insert failed: {e}")
    else:
        _set_error_message("Please fill in both title and note.")


def back_button(p1):
    """
    Navigate to the previous search result in the output notice.

    Decrements the global index and updates the displayed note content.
    If the index goes out of bounds, it is clamped and an error message is shown.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Updates the output notice content.
        - Updates the error label.
    """
    _state.index -= 1
    if 0 <= _state.index < len(_state.results):
        _update_output_notice(_state.results[_state.index][2])
        _set_error_message("")
    else:
        _set_error_message("No previous result.")
        _state.index = max(0, min(_state.index, len(_state.results) - 1))


def clear_button(p1):
    """
    Clear the input notice (text area) field.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Empties the input notice widget.
        - Clears any error message.
    """
    if _state.w and hasattr(_state.w, "inputNotice"):
        _state.w.inputNotice.delete(1.0, END)
        _set_error_message("")


def exit_button(p1):
    """
    Terminate the application immediately.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Exits the Python interpreter.
    """
    sys.exit(0)


def search_button(p1):
    """
    Search for notes whose title contains the given search term.

    The search is case‑insensitive (SQLite `LIKE` is case‑insensitive
    by default for ASCII). The first matching note is displayed in the
    output notice. Results are stored in the global state for navigation.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Updates the search results list.
        - Displays the first result (or a message if none found).
        - Updates the status/error label.
    """
    global cursor
    if not _state.w:
        return
    search_term = _state.w.inputSearchTitle.get().strip()
    if not search_term:
        _set_error_message("Please enter a search term.")
        return
    try:
        cursor.execute("SELECT * FROM notes WHERE title LIKE ?", (f"%{search_term}%",))
        _state.results = cursor.fetchall()
        _set_error_message(f"{len(_state.results)} results found.")
        _state.index = 0
        if _state.results:
            _update_output_notice(_state.results[0][2])
        else:
            _update_output_notice("No matching notes.")
    except sqlite3.Error as e:
        _set_error_message(f"Search failed: {e}")


def next_button(p1):
    """
    Navigate to the next search result in the output notice.

    Increments the global index and displays the corresponding note.
    If the search field is empty, an error is shown. If the index goes
    beyond the last result, it is clamped.

    Args:
        p1: Unused argument (required by the callback signature).

    Side effects:
        - Updates the output notice content.
        - Updates the status/error label.
    """
    if not _state.w:
        return
    search_term = _state.w.inputSearchTitle.get().strip()
    if not search_term:
        _set_error_message("Please fill the search field.")
        return
    _state.index += 1
    if 0 <= _state.index < len(_state.results):
        _update_output_notice(_state.results[_state.index][2])
        _set_error_message("")
    else:
        _set_error_message("No more results.")
        _state.index = len(_state.results) - 1


# ----------------------------------------------------------------------
# Initialization and cleanup (required by PAGE)
# ----------------------------------------------------------------------


def init(top, gui, *args, **kwargs):
    """
    Initialize the module with references to the top-level window and GUI object.

    This function is called by the PAGE‑generated code to pass the main window
    and the GUI widget (which contains the various input/output elements).

    Args:
        top: The top‑level Tkinter window.
        gui: The main GUI widget (from PAGE) that contains input/output fields.
        *args, **kwargs: Additional arguments (ignored).

    Side effects:
        - Stores references globally for use by other callback functions.
        - Also sets legacy global variables `w`, `top_level`, `root` for
          backward compatibility.
    """
    global w, top_level, root
    _state.w = gui
    _state.top_level = top
    _state.root = top
    # Legacy global variables (for old code that may reference them)
    w = gui
    top_level = top
    root = top


def destroy_window():
    """
    Close the top‑level window and release resources.

    This function is called when the application is closed.

    Side effects:
        - Destroys the top‑level Tkinter window.
        - Sets the internal reference to None.
    """
    if _state.top_level:
        _state.top_level.destroy()
        _state.top_level = None


# ----------------------------------------------------------------------
# If this module is executed directly, show a message.
# ----------------------------------------------------------------------

if __name__ == "__main__":
    import notepad

    notepad.vp_start_gui()
